version: '3.4'

services:
  catalogdb:
    image: mongo

  usersdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"

  reviewsdb:
    image: mongo

  progressdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  reviews.api:
    image: ${DOCKER_REGISTRY-}reviewsapi
    build:
      context: .
      dockerfile: src/Services/Reviews/Reviews.API/Dockerfile

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: src/Services/Users/Users.API/Dockerfile

  progresstracking.api:
    image: ${DOCKER_REGISTRY-}progresstrackingapi
    build:
      context: .
      dockerfile: src/Services/ProgressTracking/ProgressTracking.API/Dockerfile

  mongo-express:
    image: mongo-express

  pgadmin: 
    image: dpage/pgadmin4

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: src/Gateways/OcelotApiGateway/Dockerfile

  aggregator:
    image: ${DOCKER_REGISTRY-}aggregator
    build:
      context: .
      dockerfile: src/Gateways/Aggregator/Dockerfile

volumes:
  catalog_data: 
  reviews_data:
  users_data:
  pgadmin_data:
  progress_data:







