version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalog_data:/data/db

  classesdb:
    container_name: classesdb
    restart: always
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - classes_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__Host=catalogdb
      - MongoDbSettings__Port=27017
      - ApiSettings__IdentityUrl=http://identity.api:80
    depends_on:
      - catalogdb
    ports:
      - "8100:80"

  classes.api:
    container_name: classes.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__Host=classesdb
      - MongoDbSettings__Port=27018
    depends_on:
      - classesdb
    ports:
      - "8200:80"
       
  mongo-express:
    container_name: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_URL=mongodb://catalogdb:27017
    depends_on:
      - catalogdb
    ports:
      - "8081:8081"

  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - classes.api
    ports:
      - "5000:80"

  aggregator:
    container_name: aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__CatalogUrl=http://catalog.api
      - ApiSettings__ClassesUrl=http://classes.api
    depends_on:
      - catalog.api
      - classes.api
    ports:
      - "5001:80"

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__IssuerUri=http://identity.api:80
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5050:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  #web.spa:
  #  container_name: web.spa
  #  ports:
  #    - "4200:80"

