version: '3.4'

services:
  catalogdb:
    image: mongo

  classesdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  classes.api:
    image: ${DOCKER_REGISTRY-}classesapi
    build:
      context: .
      dockerfile: src/Services/Classes/Classes.API/Dockerfile

  mongo-express:
    image: mongo-express

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: src/Gateways/OcelotApiGateway/Dockerfile

  aggregator:
    image: ${DOCKER_REGISTRY-}aggregator
    build:
      context: .
      dockerfile: src/Gateways/Aggregator/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile

volumes:
  catalog_data: 
  classes_data:




