version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalog_data:/data/db

  classesdb:
    container_name: classesdb
    restart: always
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - classes_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__Host=catalogdb
      - MongoDbSettings__Port=27017
    depends_on:
      - catalogdb
    ports:
      - "8100:80"

  classes.api:
    container_name: classes.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__Host=classesdb
      - MongoDbSettings__Port=27018
    depends_on:
      - classesdb
    ports:
      - "8200:80"
       
  mongo-express:
    container_name: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER="catalogdb,classesdb"
    depends_on:
      - catalogdb
    ports:
      - "8001:8081"

  

