version: '3.4'

services:
  catalogdb:
    image: mongo

  classesdb:
    image: mongo

  usersdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  classes.api:
    image: ${DOCKER_REGISTRY-}classesapi
    build:
      context: .
      dockerfile: src/Services/Classes/Classes.API/Dockerfile

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: src/Services/Users/Users.API/Dockerfile

  mongo-express:
    image: mongo-express

  pgadmin: 
    image: dpage/pgadmin4

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: src/Gateways/OcelotApiGateway/Dockerfile

  aggregator:
    image: ${DOCKER_REGISTRY-}aggregator
    build:
      context: .
      dockerfile: src/Gateways/Aggregator/Dockerfile

volumes:
  catalog_data: 
  classes_data:
  users_data:
  pgadmin_data:





