version: '3.4'

services:
  catalogdb:
    image: mongo

  mongo-express:
    image: mongo-express

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  classes.api:
    image: ${DOCKER_REGISTRY-}classesapi
    build:
      context: .
      dockerfile: src/Services/Classes/Classes.API/Dockerfile

volumes:
  catalog_data: 
